POST http://localhost:5500/api/send-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "+91 6280077103"
}

###

# 3 HashTags to seperate 2 Requests

###

POST http://localhost:5500/api/verify-otp HTTP/1.1
Content-Type: application/json

{
    "phone": "+91 6280077103",
    "otp": 2888,
    "hash": "60867cc6645f4742b729f5df728a76cee9e89fd3fc8f4d37333f8efa5af9f32e.1628080184777"
}